import type { Locale } from '@/lib/i18n';

type Copy = { en: string; es: string };
export interface RoutePage {
  eyebrow: Copy;
  title: Copy;
  body: readonly Copy[];
  links?: readonly { href: string; label: Copy }[];
  /**
   * Imagen de cabecera opcional. SOLO para páginas cuyo activo visual ya está
   * publicado y aprobado en otro punto del sitio, o cuya fotografía llegó
   * directamente de la propietaria de la marca para ese uso — nunca para
   * introducir una imagen que implique una decisión de contenido aún no
   * tomada (ver `journal`, que se queda sin `hero` a propósito: no hay
   * fotografía editorial todavía).
   */
  hero?: { src: string; alt: Copy; focal: string; fit?: 'cover' | 'contain' };
}

const c = (en: string, es: string): Copy => ({ en, es });
export const ROUTE_PAGES: Readonly<Record<string, RoutePage>> = {
  rituals: { eyebrow: c('Find your ritual', 'Encuentra tu ritual'), title: c('What would you like to care for today?', '¿Qué quieres cuidar hoy?'), body: [c('Choose a care goal to explore products whose confirmed descriptions match that need. Recommendations use transparent rules, not diagnoses or artificial intelligence.', 'Elige un objetivo de cuidado para explorar productos cuyas descripciones confirmadas coinciden con esa necesidad. Las recomendaciones usan reglas transparentes, no diagnósticos ni inteligencia artificial.')], links: [{ href: '/shop?need=hidratacion', label: c('Hydration', 'Hidratación') }, { href: '/shop?need=textura', label: c('Texture', 'Textura') }, { href: '/shop?need=post-depilacion', label: c('Post-hair-removal care', 'Cuidado post-depilación') }] },
  sets: { eyebrow: c('Gaviota routines', 'Rutinas Gaviota'), title: c('Sets, built on real value', 'Kits basados en valor real'), body: [c('Set composition and pricing are awaiting commercial approval. We will not publish invented savings. In the meantime, build your own ritual from the verified catalog.', 'La composición y los precios de los kits esperan aprobación comercial. No publicaremos ahorros inventados. Mientras tanto, crea tu propio ritual desde el catálogo verificado.')], links: [{ href: '/rituals', label: c('Build a ritual', 'Crear un ritual') }], hero: { src: '/images/gaviota/editorial/coleccion-completa.jpg', focal: '50% 52%', fit: 'contain', alt: c('Gaviota by Lia products grouped as a complete routine set', 'Productos Gaviota by Lia agrupados como kit de rutina completa') } },
  ingredients: { eyebrow: c('Ingredient education', 'Educación de ingredientes'), title: c('Transparency before claims', 'Transparencia antes que promesas'), body: [c('The complete INCI lists are pending manufacturer documentation. We will publish each ingredient, cosmetic function and related product only after confirmation.', 'Las listas INCI completas están pendientes de documentación del fabricante. Publicaremos cada ingrediente, su función cosmética y productos relacionados solo después de confirmarlos.')], links: [{ href: '/contact', label: c('Ask about a product', 'Consultar sobre un producto') }], hero: { src: '/images/gaviota/editorial/coleccion-completa.jpg', focal: '50% 45%', alt: c('The complete Gaviota by Lia product line arranged together', 'La línea completa de productos Gaviota by Lia dispuesta en conjunto') } },
  'our-story': { eyebrow: c('Our story', 'Nuestra historia'), title: c('Body care made as a moment of your own', 'Cuidado corporal como un momento propio'), body: [c('Gaviota by Lia is a Dominican-inspired body-care brand focused on intentional routines, warm sensoriality and clear product education.', 'Gaviota by Lia es una marca de cuidado corporal de inspiración dominicana, enfocada en rituales intencionales, sensorialidad cálida y educación clara sobre cada producto.')], links: [{ href: '/founder', label: c('Meet the founder', 'Conocer a la fundadora') }, { href: '/shop', label: c('Explore the collection', 'Explorar la colección') }], hero: { src: '/images/gaviota/editorial/story-fundadora.jpg', focal: '50% 28%', alt: c('Portrait of Marlene Dietsch, founder of Gaviota by Lia', 'Retrato de Marlene Dietsch, fundadora de Gaviota by Lia') } },
  founder: { eyebrow: c('The founder', 'La fundadora'), title: c('A personal vision of everyday care', 'Una visión personal del cuidado diario'), body: [c('This page intentionally avoids biographical claims that have not yet been approved for publication. The founder’s full story is on its way.', 'Esta página evita intencionalmente datos biográficos que aún no han sido aprobados para publicación. La historia completa de la fundadora está en camino.')], hero: { src: '/images/gaviota/founder/fundadora-6.jpg', focal: '50% 22%', alt: c('Marlene Dietsch, founder of Gaviota by Lia', 'Marlene Dietsch, fundadora de Gaviota by Lia') } },
  journal: { eyebrow: c('Beauty Notes', 'Beauty Notes'), title: c('Care, routines and ingredients', 'Cuidado, rituales e ingredientes'), body: [c('No articles are published yet. The journal will open with reviewed educational content rather than placeholder posts.', 'Aún no hay artículos publicados. El diario se abrirá con contenido educativo revisado, no con publicaciones de relleno.')] },
  faq: { eyebrow: c('Help', 'Ayuda'), title: c('Frequently asked questions', 'Preguntas frecuentes'), body: [c('Product, payment, shipping and return answers depend on approved business policies. Send us your question while those policies are finalized.', 'Las respuestas sobre productos, pagos, envíos y devoluciones dependen de políticas comerciales aprobadas. Envíanos tu consulta mientras se finalizan.')], links: [{ href: '/contact', label: c('Contact us', 'Contáctanos') }] },
  contact: { eyebrow: c('Customer care', 'Atención al cliente'), title: c('How can we help?', '¿Cómo podemos ayudarte?'), body: [c('The secure support form and transactional email provider are being connected. For now, contact the brand through its verified Instagram profile.', 'El formulario seguro de soporte y el proveedor de correo transaccional están en proceso de conexión. Por ahora, contacta a la marca mediante su perfil verificado de Instagram.'), c('Gaviota By Lia LLC — 5 Rangeley Avenue, Providence, RI 02908, United States.', 'Gaviota By Lia LLC — 5 Rangeley Avenue, Providence, RI 02908, Estados Unidos.')], links: [{ href: 'https://www.instagram.com/gaviotabylia/', label: c('Message on Instagram', 'Escribir por Instagram') }] },
  'track-order': { eyebrow: c('Orders', 'Pedidos'), title: c('Track your order', 'Seguir mi pedido'), body: [c('Order lookup will be enabled with rate limiting and a generic response once the order service is connected. It is not exposed prematurely because that could leak customer information.', 'La consulta de pedidos se habilitará con rate limiting y respuesta genérica cuando se conecte el servicio de órdenes. No se expone antes porque podría filtrar información de clientes.')], links: [{ href: '/contact', label: c('Get help', 'Obtener ayuda') }] },
  'shipping-policy': { eyebrow: c('Policies', 'Políticas'), title: c('Shipping policy', 'Política de envíos'), body: [c('Rates, delivery zones and processing times require business approval before publication. See LEGAL_TODO.md for the exact missing decisions.', 'Las tarifas, zonas de entrega y tiempos de preparación requieren aprobación comercial antes de publicarse. Consulta LEGAL_TODO.md para las decisiones faltantes.')] },
  'refund-policy': { eyebrow: c('Policies', 'Políticas'), title: c('Return and refund policy', 'Política de devoluciones y reembolsos'), body: [c('Return windows, hygiene exclusions and refund procedures are awaiting legal approval. No terms are invented here.', 'Los plazos de devolución, exclusiones por higiene y procedimientos de reembolso esperan aprobación legal. Aquí no se inventan condiciones.')] },
  'privacy-policy': { eyebrow: c('Policies', 'Políticas'), title: c('Privacy policy', 'Política de privacidad'), body: [c('The final controller identity, contact details, processors and retention periods must be approved before launch.', 'La identidad final del responsable, datos de contacto, encargados y plazos de conservación deben aprobarse antes del lanzamiento.')] },
  terms: { eyebrow: c('Policies', 'Políticas'), title: c('Terms and conditions', 'Términos y condiciones'), body: [c('Commercial identity, jurisdiction and sale terms remain under legal review. This route exists without publishing fabricated legal language.', 'La identidad comercial, jurisdicción y condiciones de venta siguen bajo revisión legal. Esta ruta existe sin publicar lenguaje legal inventado.')] },
  cookies: { eyebrow: c('Privacy choices', 'Opciones de privacidad'), title: c('Cookie policy', 'Política de cookies'), body: [c('Only necessary application storage is currently used. Analytics and marketing scripts will remain disabled until consent controls and final vendors are approved.', 'Actualmente solo se usa almacenamiento necesario para la aplicación. Analítica y marketing seguirán desactivados hasta aprobar controles de consentimiento y proveedores finales.')] },
};

export const localizedCopy = (copy: Copy, locale: Locale) => copy[locale];
